base/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path

from . import views

urlpatterns = [
    # Home page
    path("", views.index, name='index'),
    # Show all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic
    path('topics/<topic_id>', views.topic, name='topic'),
    # Page for adding a new topic
    # path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<topic_id>', views.new_entry, name='new_entry'),
    # Page for editing an entry
    path('edit_entry/<entry_id>', views.edit_entry, name='edit_entry'),
]

basic_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls','base'), namespace='base')),
    path('users/', include(('users.urls','users'), namespace='users')),
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls','base'), namespace='base')),
    path('users/', include(('users.urls','users'), namespace='users')),
]

users/urls.py
"""Defines URL patterns for users"""
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings


from django.contrib.auth.views import LoginView
from . import views
urlpatterns = [
    # Login page
    path('login/', LoginView.as_view(template_name= 'users/login.html'), name='login'),
    # Logout page
    path('logout/', views.logout_view, name='logout'),
    # Registration page
    path('register/', views.register, name='register'),
    # Profile
    path('profile/', views.profile, name='profile'),
]

base/models.py
from email.policy import default
from io import open_code
from pyexpat import model

from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
# Create your models here.
class Topic(models.Model):

    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    content= RichTextField(null= True, blank= True)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    def __str__(self):

        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):

    """Something specific learned about a topic"""
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        default= None
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default= None
    )
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    updated_date= models.DateTimeField(auto_now=True)
    active= models.BooleanField(default= True)
    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):

        """Return a string representation of the model."""
        return self.text[:50] + "..."

# class ItemBased(models.Model):
#     class Meta:
#         abstract= True
#     subject = models.CharField(max_length=255 )
#     created_date= models.DateTimeField(auto_now_add= True)
#     updated_date= models.DateTimeField(auto_now=True)
#     active= models.BooleanField(default= True)
    
#     def __str__(self):
#         return self.subject


# class Lession(ItemBased):
#     class Meta:
#             unique_together= ('subject', 'course')
#     image= models.ImageField(upload_to= 'static/images/%Y/%m', default= None)
#     course= models.ForeignKey(
#             Topic,
#             on_delete= models.CASCADE
#             )
#     tags= models.ManyToManyField('Tag', blank=True, null= True)   

# class Tag(models.Model):
#     name= models.CharField(max_length= 50, unique= True)

#     def __str__(self):
#         return self.name

base/forms.py
from django import forms

from .models import Topic, Entry
from django.contrib.auth import get_user_model

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
 class Meta:
    model = Entry
    fields = ['text']
    labels = {'text': ''}
    widgets = {'text': forms.Textarea(attrs={'cols': 80})}

base/views.py
#
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.utils.html import format_html
#
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    """The home page for Learning Log"""
    return render(request, 'base/index.html')


def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'base/topics.html', context)


def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    # if topic.owner != request.user:
    #     raise Http404
    list_display = ['content', ]
    def get_content(self, obj):
        format_html(obj)
    

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'base/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
    # No data submitted; create a blank form.
        form = TopicForm()
    else:
    # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('base:topics'))
    context = {'form': form}
    return render(request, 'base/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
    # No data submitted; create a blank form.
        form = EntryForm()
    else:
    # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return HttpResponseRedirect(reverse('base:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'base/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
    # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
    # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'base/edit_entry.html', context)

base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Canopy</title>
        
        <link rel="stylesheet" href="{% static 'css/freestyle.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
        <link rel="icon" type="image/png" href="{% static 'images/logo.jpg' %}" />
        
    </head>

    <body>
        <script src="{% static 'js/main.js' %}"></script>
        <header class="p-3 bg-dark text-white">
            <div class="container">
              <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="{% url 'base:index' %}" class="col-2 d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img class="login_logo_img" src="{% static 'images/logo.jpg'%}" style="max-height:30px">
                    Canopy
                </a>
        
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                  <li><a href="{% url 'base:topics' %}" class="nav-link px-2 text-white">Bài viết</a></li>

                </ul>
                <div class="text-end">
                  {% if user.is_authenticated %}
                  <a class="btn text-white me-2">Hello, {{ user.username }}</a>
                  <a class="btn btn-warning" href="{% url 'users:logout' %}">Đăng xuất</a>
                  {% else %}
                  <a class="btn btn-outline-light me-2" href="{% url 'users:register' %}">Đăng ký</a>
                  <a class="btn btn-warning" href="{% url 'users:login' %}">Đăng nhập</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </header>

        <div class="container">
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </div> <!-- /container -->
           
    </body>

base/templates/base/edit_entry.html
{% extends "base/base.html" %}

{% block content %}

    <p><a href="{% url 'base:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>
    <form action="{% url 'base:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>save changes</button>
    </form>

{% endblock content %}

base/templates/base/index.html
{% extends "base/base.html" %}
{% load static %}
{% block header %}

{% endblock header %}

{% block content %}
<style>
    .home{
                position: absolute;
                left: 0px;
                top: 72px;         
                height: 100vh;
                width: 100vw;
                background-color: #F6D565;
            }
    
</style>
<img class="home" src="{% static 'images/home.jpg'%}">
{% endblock content %}

base/templates/base/new_entry.html
{% extends "base/base.html" %}

{% block content %}

    <p><a href="{% url 'base:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'base:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>add entry</button>
    </form>

{% endblock content %}

base/templates/base/new_topic.html
{% extends "base/base.html" %}

{% block content %}

 <p>Thêm bài viết mới:</p>

    <form action="{% url 'base:new_topic' %}" method='post'>
    {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Thêm bài viết</button>
    </form>

{% endblock content %}

base/templates/base/topic.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<style>
    #home {
        position: absolute;
        left: 0px;
        top: 72px;
        height: 100vh;
        width: 100vw;
        /* background-color: #F6D565; */
    }

    .text {
        position: absolute;
        left: 50px;
        top: 120px;
    }

    .topic {
        position: absolute;
        left: 50px;
        top: 80px;
    }

    .newtopic {
        position: absolute;
        left: 50px;
        top: 180px;
    }
</style>

<div class="home ">
    <p class="topic">Bài viết: {{topic}}</p>
    <div class="text">
        {{topic.content|safe}}


        <div class="row d-flex justify-content-center">
            <div class="col-md-8 col-lg-6">
                <div class="card shadow-0 border" style="background-color: #f0f2f5;">
                    <div class="card-body p-4">

                        <form class="card mb-4" action="{% url 'base:new_entry' topic.id %}" method='post'>
                            {% csrf_token %}
                            <p>
                                <textarea class="form-control" placeholder="Type comment..." name="text" cols="80"
                                    rows="2" required="" id="id_text"></textarea>
                            </p>
                            <button class="btn btn-primary col-4 " name="submit">thêm bình luận</button>
                        </form>
                        {% for entry in entries %}
                        <div class="card mb-4">
                            <div class="card-body">
                                <p>{{ entry.text|linebreaks }}</p>
                                <div class="d-flex justify-content-between">
                                    <div class="d-flex flex-row align-items-center">

                                        <img src="https://t4.ftcdn.net/jpg/04/08/24/43/360_F_408244382_Ex6k7k8XYzTbiXLNJgIL8gssebpLLBZQ.jpg" alt="avatar" width="25"
                                            height="25" />
                                        <p class="small mb-0 ms-2">{{ entry.owner }}</p>
                                    </div>
                                    <div class="d-flex flex-row align-items-center">
                                        <p class="small text-muted mb-0" style="max-height:5px">{{entry.date_added|date:'M d, Y H:i'}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                        <li>
                            Chưa có bình luận nào
                        </li>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

base/templates/base/topics.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
    <style>
        .home{
                position: absolute;
                left: 0px;
                top: 72px;         
                height: 100vh;
                width: 100vw;
                background-color: #F6D565;
            }
        .text{
            position: absolute;
            left: 50px;
            top: 120px;
        }
        .topic{
            position: absolute;
            left: 50px;
            top: 80px;
        }
        .newtopic{
            position: absolute;
            left: 50px;
            top: 180px;
        }
    </style>
    <img src="{% static 'images/topic_background.jpg'%}"  class="home">
    <p class="topic"> Bài viết</p>
    <ul class="text">
        {% for topic in topics %}
            <li > 
                <a href="{% url 'base:topic' topic.id %}">{{ topic }}</a> 
            </li> 
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
    

{% endblock content %}